export const Auth = {
  SET_USER_SUCCESS: 'SET_USER_SUCCESS',
  SET_USER_FAILURE: 'SET_USER_FAILURE',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
};

export const ToDo = {
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILURE: 'CREATE_TODO_FAILURE',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
  GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',
};

export const Profile = {
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  EDIT_FILE_FAILURE: 'EDIT_FILE_FAILURE',
  EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',
};

export const Task = {
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_FAILURE: 'CREATE_TASK_FAILURE',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_FAILURE: 'GET_TASKS_FAILURE',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_FAILURE: 'UPDATE_TASK_FAILURE'
};
